[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "pybr"
dynamic = ["version"]
description = "Collection of utilities for Brazilian data and formats"
authors = [
    { name = "Gustavo Efeiche", email = "gustavo.efeiche@gmail.com" }
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/effeix/pybr"
repository = "https://github.com/effeix/pybr"
keywords = ["brazil", "portuguese", "utilities", "cpf", "cnpj"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Internationalization",
    "Topic :: Software Development :: Localization",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
]
requires-python = ">=3.10"
dependencies = []
[dependency-groups]
dev = [
    "nox>=2025.11.12",
    "pytest>=9.0.1",
]

[project.scripts]
pybr = "pybr:main"

[project.urls]
Homepage = "https://github.com/effeix/pybr"

[tool.hatch.build.hooks.vcs]
version-file = "src/pybr/_version.py"

[tool.hatch.version]
source = "vcs"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
publish-url = "https://upload.pypi.org/legacy/"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
